services:
  postgres:
    image: postgres:15
    container_name: reservation-system-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservation_system
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  adminer:
      image: adminer
      container_name: reservation-system-adminer
      ports:
        - "8080:8080"
volumes:
  postgres_data:

  
